### ISSUE TITLE
Which version of Flamenco & Blender

### ISSUE THREAD

**Issue by drsybren** [dblanque/flamenco-compositor-script#1]
Hey there!

Could you please update the README.md and the job compiler script itself so that it documents which version of Flamenco & Blender this script supports? Then I'll copy that info to the Flamenco website itself.

Thanks!

**Comment by dblanque** [comment]
Hey Sybren, I haven't tested this out in quite a long time but I'll see if I can spin up some test environment and check that out for ya.

**Comment by drsybren** [comment]
When you share your script, please also keep it up to date. If it gets outdated or abandoned, I'll have to remove it.

**Comment by dblanque** [comment]
> When you share your script, please also keep it up to date. If it gets outdated or abandoned, I'll have to remove it.

Hey!
Yeah sorry, just been very busy with other projects.

Will update soon.

**Comment by dblanque** [comment]
Hey Sybren,

Tested with Blender 4.0 from a Windows Client to a Linux SAMBA Container with Shaman enabled.
Changed a variable name for easier comprehension and applied minor fix for incorrect variable usage in `multi_pass_render.js`

Commit #6cbcb1d

Let me know if there are any further issues.
Regards,
Dylan

**Comment by drsybren** [comment]
> Tested with Blender >= 4.0 and Flamenco >= 3.5

This feels a bit misleading. There is no Flamenco newer than 3.5, so you can't really claim that this script is tested with anything beyond that. Also you don't know for sure whether it'll work with 3.6 when that's released, until you test it.

Also, and this is a bit pedantic, I know, but for me "tested with" or "works with" are two very different things. I can test with Blender 1.6 and see that it doesn't work -- and still claim "tested with Blender 1.6" ;-)

If it works with Blender 4.0-4.1 and Flamenco 3.5, just write that, it'll be clearer.

**Comment by dblanque** [comment]
>This feels a bit misleading. There is no Flamenco newer than 3.5, so you can't really claim that this script is tested with anything >beyond that. Also you don't know for sure whether it'll work with 3.6 when that's released, until you test it.

This is a logical correction. I will apply the changes to eliminate any misunderstandings.

>Also, and this is a bit pedantic, I know, but for me "tested with" or "works with" are two very different things. I can test with Blender 1.6 and see that it doesn't work -- and still claim "tested with Blender 1.6" ;-)

The context of development is not the same as that of a published repository, therefore it would be coherent to assume that something that was tested, and then released and marked as tested, therefore _works_. This seems like a -how some would call it...- nitpick.

I will however change it as a gesture of goodwill.

_LLAP_

**Comment by drsybren** [comment]
I've updated the website at https://flamenco.blender.org/third-party-jobs/compositor-script/
